# Generated by Django 6.0.7 on 2026-09-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tickettype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='quaantity',
            new_name='quantity',
        ),
    ]
